### ISSUE TITLE
Suggestion: Allow configurable matching thresholds for reporting

### ISSUE THREAD

**Issue by sgrigson** [eigenmagic/fediblockhole#28]
A bit of a piggyback on the 'allowlist' idea (which works great).

One list I've really wanted to create is a "match" between trusted sources according to a certain threshold. Not sure whether that threshold should be numeric or percentage-based.

Example:

Source A, B, and C all have `badsite1.com` in their database. Sources D, E, F, and G do not.

Option 1:

`num_matches_required` (defaults to 0). 0 is legacy behavior. With num_matches_required of 5, a source would need to be listed by 5 different sources in order to be included.

`percentage_matches_required` (defaults to 0). 0 is legacy behavior. With percentage_matches_required of 50% (or 50), You'd need 50% or greater of the total number of sources to match.

Percentage would work consistently without having to update the percentage.

On the other hand, "num_matches_required" is a lot simpler, I would imagine, and would match my need. If I could say "This merge file should only contain domains agreed upon by at least two of the sources" that would eliminate a lot of isolated "randomness" from the file.

Especially if you wanted to sync only the most severe of defederations that have a large amount of consensus behind it, you could require any blocks in the file to achieve at least 3-5 matches.

Really appreciate your work and responsiveness. Don't burn yourself out, but this is a very nice project, I must say.

**Comment by jpwarren** [comment]
That's a neat idea.

It might be a bit fiddly to implement given the current code structure. I'll have to think about it for a bit to see what changes will be needed to support this functionality.

**Comment by jpwarren** [comment]
It's not too bad. The `apply_mergeplan()` code will need to change, but I think implementing this feature will actually improve the overall code structure.

I'd prefer to use pct mode because it seems more flexible, but it could also be a lot more complex to reason about, which might lead people to surprise themselves with how the tool works.

For example: I pull in the blocklist from my own instance as a baseline source, and merge other lists with it. With number mode, I could just increase the threshold by 1, but with pct mode, it gets more complex.

The method of threshold calculation is fairly straightforward to change in the code, but the change in outcome could be substantial. Supporting both modes would be more complex, but doable. I'd prefer to pick a single method if possible.

More testing and experimenting needed to see what works well in practice.

**Comment by jpwarren** [comment]
Added this feature on a branch: https://github.com/eigenmagic/fediblockhole/tree/allowlist-thresholds

**Comment by sgrigson** [comment]
I'll give this a look

**Comment by sgrigson** [comment]
There's a weird bug in this branch, when saving intermediary files.

Normally when I pull from, say, `mastodon.social` the resulting intermediate file is named `mastodon.social.csv`

In this branch (only) that file becomes named something like `http:--mastodon.social/instances/something/something.csv`

Additionally, I see this:

`merged = merge_blocklists(blocklists, conf.mergeplan)`

But notice it's not passing over `conf.threshold` and `conf.threshold_type` to that function. So the new params for the function exist, but I don't think it's actually called anywhere in the branch.

**Comment by sgrigson** [comment]
@jpwarren Did you see these issues I mentioned? I don't believe the thresholds are getting passed to the merge_blocklists function, also the file format when saving intermediate files from remote sources seems to have changed, though I have not tested since you merged the changes.

**Comment by jpwarren** [comment]
The logging/export of blocklist sources has changed a bit because of how the origin of a domain block is now recorded. The origin is more URL based for remote sources, and internal processing steps are easier to determine when logging.

There's a new `DomainBlock` object and a `Blocklist` object to contain them so we don't have to pass variables around all over the place, which is why the logging/export needed to change.

**Comment by jpwarren** [comment]
The lack of config parameters was because I hadn't properly finished implementing the functionality. It's done now and will be included in the pending release v0.4.3.

**Comment by jpwarren** [comment]
Functionality added: #44

**Comment by sgrigson** [comment]
Oh! Thank you!!

**Comment by sgrigson** [comment]
Just tested this out a bit after upgrading.

This is a huge step forward and really nice work.

**Comment by sgrigson** [comment]
I don't have anything to add to this, so I'm content to close the issue. I think you nailed this one.
