### ISSUE TITLE
Allow reading from non-admin domain_blocks endpoint

### ISSUE THREAD

**Issue by ineffyble** [eigenmagic/fediblockhole#6]
Reading from the admin domain_blocks endpoint is great when an instance has not made their blocks visible. However, it does require an API key to be generated by a remote admin.

Many instances have their domain blocks visible to all users, meaning that hitting the regular domain_blocks endpoint with an API key associated with a regular user will work.

Some instances have their domain blocks visible publicly, meaning that hitting the regular domain_blocks endpoint without an API key will work.

Ideally fediblockhole would let you sync with remote instances using these two other options, so that, for example, a small instance can copy blocks from a trusted big instance, without needing the admins of the big instance to provide admin API access.

**Comment by jpwarren** [comment]
Hmm, good idea!

How do you think this should be configured?

My initial thought is to have it be in the same `blocklist_instance_sources` section, but if the token is missing, the tool uses the regular `domain_blocks` endpoint instead of the admin one.

**Comment by jpwarren** [comment]
A quick test indicates this isn't enough. 

No `token` can mean try to use the regular API, but this doesn't help us if we want to use the regular API with a non-admin token.

We need to distinguish between an admin `domain_block` and a user `domain_block` because the tool has no way of knowing if a token is authorized for admin access or just regular user access.

We could try to use the admin endpoint first, and then fall back to regular user if that fails, but that's an extra set of network accesses and additional load on remote instances that we may or may not have informed we want to hit with this extra traffic. Better to reduce the overall work done by the tool, and the load on other people's kit, by doing a little bit of extra config work ourselves just once.

I propose adding a `type` field to the `blocklist_instance_sources` config that defaults to non-admin, but if `type=admin` then the tool uses the admin API endpoint.

Also, if the token is missing, then the tool assumes you want the user endpoint with no authorization.

**Comment by jpwarren** [comment]
A further thing to consider: right now, if the fetch fails, the tool hard fails with an error that attempts to help you figure out why it failed.

I prefer to hard-fail to encourage people to fix things properly rather than attempt to muddle through and then forget to ever getting around to fixing things properly.

But is this appropriate here? Should the tool try to continue processing, or should it keep this hard-fail behaviour?

For now I will continue with hard-fail, but I am open to being convinced this should change.

**Comment by jpwarren** [comment]
Alas! It appears that the current Mastodon API requires a user.

See https://github.com/mastodon/mastodon/blob/main/app/controllers/api/v1/domain_blocks_controller.rb line 8

I'll leave in the code to support public access to the domain blocks API endpoint so that it'll start working if/when the Mastodon API supports it.

**Comment by ineffyble** [comment]
@jpwarren How are you able to go to https://hachyderm.io/about when logged out and expand "Moderated servers" then? I can see it's making an AJAX call to domain_blocks.

**Comment by ineffyble** [comment]
`curl https://hachyderm.io/api/v1/instance/domain_blocks` works.

**Comment by ineffyble** [comment]
You want https://github.com/mastodon/mastodon/blob/main/app/controllers/api/v1/instances/domain_blocks_controller.rb
